### PR TITLE
Gits pull #11

### PR DESCRIPTION
**Pull request by rhnprabhune**
Working on gits pull functionality

### CODE REVIEW

**Comment by ramyasaimullapudi** [comment]
git simplified is to ease the user experience. So, giving as few parameters as possible and reduce syntax is the ultimate goal.
The existing git pull will pull from the master and update the current branch.
So I think this is not necessary. 
Let's take others inputs too

**Comment by rhnprabhune** [comment]
The aim of this was that user shouldn't be required to switch between gits and git commands. So the intention was the GITS should cover all the basic functionalities as well. But yes, this doesn't simplify any syntax.

**Comment by ramyasaimullapudi** [comment]
okay then let's merge this. But I see some conflicts. Once they are resolved, let's push this in.

**Review by arjunptm — APPROVED** [review]
Looks good to me, can merge!

**Pull request merged**
